baseURL = 'https://[username].github.io/[repository]'
languageCode = 'ar'
title = 'دليل السعادة التفاعلي: إزاي أفرح؟'
theme = ''

[params]
  description = 'دليل تفاعلي للساعة والفرح من خلال أربعة محاور رئيسية'
  author = 'Your Name'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
