baseURL = 'https://portfoliohubs.github.io/sanwy'
languageCode = 'ar'
title = 'دليل السعادة التفاعلي: إزاي أفرح؟'

[params]
  description = 'دليل تفاعلي للساعة والفرح من خلال أربعة محاور رئيسية'
  author = 'Your Name'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
  
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
